# Generated by Django 6.0.1 on 2026-03-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eik', models.CharField(max_length=13, unique=True, verbose_name='ЕИК на доставчик')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Име на доставчик')),
                ('percent_condition', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент бонус')),
                ('payment_terms', models.ManyToManyField(blank=True, related_name='suppliers', to='bonuspercent.paymentterm')),
                ('categories', models.ManyToManyField(blank=True, to='bonuspercent.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasing_amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('condition_eik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttlpurchases', to='bonuspercent.conditionspercent')),
            ],
        ),
    ]
