# Generated by Django 6.0.1 on 2026-01-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eik', models.CharField(max_length=13, unique=True, verbose_name='ЕИК на доставчик')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Име на доставчик')),
                ('percent_condition', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Процент бонус')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eik', models.CharField(max_length=13, unique=True, verbose_name='ЕИК на доставчик')),
                ('purchasing_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стойност покупка')),
            ],
        ),
    ]
