# Generated by Django 6.0.1 on 2026-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuspercent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingamount',
            name='eik',
            field=models.CharField(max_length=13, verbose_name='ЕИК на доставчик'),
        ),
    ]
