# Generated by Django 6.0.1 on 2026-02-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuspercent', '0002_alter_purchasingamount_eik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasingamount',
            name='eik',
        ),
        migrations.AddField(
            model_name='purchasingamount',
            name='condition_eik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttlpurchases', to='bonuspercent.conditionspercent'),
        ),
        migrations.AlterField(
            model_name='purchasingamount',
            name='purchasing_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
