# Generated by Django 6.0.1 on 2026-02-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuspercent', '0003_remove_purchasingamount_eik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingamount',
            name='condition_eik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ttlpurchases', to='bonuspercent.conditionspercent'),
            preserve_default=False,
        ),
    ]
