# Generated by Django 6.0.1 on 2026-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuspercent', '0004_alter_purchasingamount_condition_eik'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='conditionspercent',
            name='categories',
            field=models.ManyToManyField(blank=True, to='bonuspercent.productcategory'),
        ),
    ]
