# Generated by Django 6.0.1 on 2026-03-21 13:27

import contract_documents.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuspercent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), contract_documents.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuspercent.conditionspercent')),
            ],
        ),
    ]
