# Generated by Django 6.0.1 on 2026-03-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoConditionsPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=9, unique=True, verbose_name='ID на продукт')),
                ('product_name', models.CharField(max_length=20, verbose_name='Име на продукт')),
                ('purchasing_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Покупна цена за изчисление на отстъпката')),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент отстъпка за промоционалните продажби')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество продажби')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuspromo.promoconditionspercent')),
            ],
        ),
    ]
