# Generated by Django 6.0.1 on 2026-02-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuspromo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesqty',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuspromo.promoconditionspercent'),
        ),
    ]
